# DIP Homework Assignment #4
# Date: Mar 7, 2019
# Name: Yu-Ting, TSENG
# ID #: B05902120
# email: b05902120@ntu.edu.tw
# compiled on MacBook (Unix) with g++

All: Problem1

Problem1:
	@echo =========== Problem1 ===========
	@echo Compiling the code Problem1_a.cpp
	g++ Problem1_a.cpp -o Problem1_a
	@echo  
	@echo Executing the executable file Problem1_a
	./Problem1_a
	@echo --------------------------------
	@echo Compiling the code Problem1_b.cpp
	g++ Problem1_b.cpp -o Problem1_b
	@echo  
	@echo Executing the executable file Problem1_b
	./Problem1_b
	@echo --------------------------------
	@echo Compiling the code Problem1_c.cpp
	g++ Problem1_c.cpp -o Problem1_c
	@echo  
	@echo Executing the executable file Problem1_c
	./Problem1_c
	@echo --------------------------------
	@echo Compiling the code Problem1_d.cpp
	g++ Problem1_d.cpp -o Problem1_d
	@echo  
	@echo Executing the executable file Problem1_d
	./Problem1_d
	@echo ================================
	@echo  

clean: 
	rm -rf *.raw 