# DIP Homework Assignment #ˇ
# Date: Mar 7, 2019
# Name: Yu-Ting, TSENG
# ID #: B05902120
# email: b05902120@ntu.edu.tw
# compiled on MacBook (Unix) with g++

All: Problem1 Problem2 Bonus

Problem1:
	@echo =========== Problem1 ===========
	@echo Compiling the code Problem1_a.cpp
	g++ Problem1_a.cpp -o Problem1_a
	@echo  
	@echo Executing the executable file Problem1_a
	./Problem1_a
	@echo --------------------------------
	@echo Compiling the code Problem1_b.cpp
	g++ Problem1_b.cpp -o Problem1_b
	@echo  
	@echo Executing the executable file Problem1_b
	./Problem1_b
	@echo --------------------------------
	@echo Compiling the code Problem1_c1.cpp
	g++ Problem1_c1.cpp -o Problem1_c1
	@echo  
	@echo Executing the executable file Problem1_c1
	./Problem1_c1
	@echo --------------------------------
	@echo Compiling the code Problem1_c2.cpp
	g++ Problem1_c2.cpp -o Problem1_c2
	@echo  
	@echo Executing the executable file Problem1_c2
	./Problem1_c2
	@echo ================================
	@echo  

Problem2: 
	@echo =========== Problem2 ===========
	@echo Compiling the code Problem2_ab.cpp
	g++ Problem2_ab.cpp -o Problem2_ab
	@echo  
	@echo Executing the executable file Problem2_ab
	./Problem2_ab
	@echo --------------------------------
	@echo Compiling the code Problem2_c.cpp
	g++ Problem2_c.cpp -o Problem2_c
	@echo  
	@echo Executing the executable file Problem2_c
	./Problem2_c
	@echo ================================
	@echo  

Bonus: 
	@echo =========== Problem2 ===========
	@echo Compiling the code Bonus_1.cpp
	g++ Bonus_1.cpp -o Bonus_1
	@echo  
	@echo Executing the executable file Bonus_1
	./Bonus_1
	@echo --------------------------------
	@echo Compiling the code Bonus_2.cpp
	g++ Bonus_2.cpp -o Bonus_2
	@echo  
	@echo Executing the executable file Bonus_2
	./Bonus_2
	@echo --------------------------------
	@echo Compiling the code Bonus_3.cpp
	g++ Bonus_3.cpp -o Bonus_3
	@echo  
	@echo Executing the executable file Bonus_3
	./Bonus_3
	@echo ================================
	@echo 

clean: 
	rm -rf *.raw 